use_frameworks!

target 'AwesomeMedia_Example' do
  pod 'AwesomeMedia', :path => '../'
  pod 'AwesomeUIMagic', git: 'https://github.com/iOSWizards/AwesomeUIMagic', tag: '0.4.6'
  pod 'AwesomeLoading', git: 'https://github.com/Mindvalley/Mobile_iOS_Library_AwesomeLoading.git', tag: '0.1.3'
  pod 'AwesomeNetwork', git: 'https://github.com/iOSWizards/AwesomeNetwork', tag: '0.1.4'

  target 'AwesomeMedia_Tests' do
    inherit! :search_paths

    
  end
end
