use_frameworks!

target 'AwesomeMedia_Example' do
  pod 'AwesomeMedia', :path => '../'
  pod 'AwesomeUIMagic', git: 'https://github.com/iOSWizards/AwesomeUIMagic', tag: '0.4.7'
  pod 'AwesomeImage', git: 'https://github.com/iOSWizards/AwesomeImage', tag: '0.1.4'
  pod 'AwesomeLoading', git: 'https://github.com/iOSWizards/AwesomeLoading.git', tag: '0.1.5'
  pod 'AwesomeNetwork', git: 'https://github.com/iOSWizards/AwesomeNetwork', tag: '0.1.4'
  pod 'AwesomeDownloading', git: 'https://github.com/iOSWizards/AwesomeDownloading', tag: '0.1.2'
  pod 'AwesomeCore', git: 'https://github.com/mindvalley/Mobile_iOS_Library_AwesomeCore.git', tag: '0.14.4'
  pod 'AwesomeConstants', git: 'https://github.com/Mindvalley/Mobile_iOS_Library_AwesomeConstants.git', tag: '0.2.0'
  pod 'AwesomeTracking', git: 'https://github.com/Mindvalley/Mobile_iOS_Library_AwesomeTracking.git', tag: '0.1.4'

  target 'AwesomeMedia_Tests' do
    inherit! :search_paths

    
  end
end
