# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.3
language: objective-c
xcode_project: Example/AwesomeMedia.xcworkspace # path to your xcodeproj folder
xcode_scheme: AwesomeMedia
# cache: cocoapods
podfile: Example/Podfile
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install --project-directory=Example
script:
- xcodebuild -workspace Example/AwesomeMedia.xcworkspace -scheme AwesomeMedia #-sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
#- xcodebuild CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -workspace Example/AwesomeMedia.xcworkspace -scheme AwesomeMedia-Example
